image: node:latest
stages:
- production
production:
type: deploy
stage: production
image: ruby:latest
script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=udemy-online-courses App --api-key=5a2afa00-0fc0-4048-b5f8-efc473250a34
only:
    - develop